---
theme: dark
jwt_secret: kai4SfT1IkQsqr3riMy8NAdmIjCAviTdNuvMd1wGArAh0o4rp3FFhgnn588X3uhA 
default_redirection_url: https://auth.solutioneer.app 

server:
  host: 0.0.0.0 ##- The address to listen on. 
  port: 9091 ##- The port to listen on.

log:
  level: debug
  format: json ##- Format the logs are written as: json, text.
  file_path: /config/logs/authelia.log  ##- File path where the logs will be written. 

totp:
  disable: false
  issuer: authelia.com
  algorithm: sha1
  digits: 6
  period: 30
  skew: 1
  secret_size: 32
  
authentication_backend: ## Available: `file`, `ldap`. Must only use one providers.
  password_reset: ## Password Reset Options.
    disable: false ## Disable HTML element and API for password reset
  refresh_interval: 5m 
  file:
    path: /config/users_database.yml
    password: 
      algorithm: argon2
      argon2:
        variant: argon2id
        iterations: 1
        memory: 65536
        parallelism: 8
        key_length: 32 ## default length
        salt_length: 16
        
password_policy:
  standard:              
    enabled: false ##> Do not!!!!! enable to enforce password policy
    min_length: 8 ##- Require a minimum length for passwords.
    max_length: 0 ##- Require a maximum length for passwords.
    require_uppercase: true ##- Require uppercase characters.
    require_lowercase: true ##- Require lowercase characters.
    require_number: true ##- Require numeric characters.
    require_special: true ##- Require special characters.
  
access_control:
  default_policy: deny
  rules: #> SECURITY: Explisitely allow only the following domains.
    #> Rules applied to everyone 
    - domain: auth.solutioneer.app #> Authenticator domain
      policy: bypass
    #> Sub-domains to protect    
    - domain: passbolt.solutioneer.app
      policy: one_factor
    ##> Rules applied to 'admins' group
    - domain: 'proxmox.solutioneer.app'
      subject: 'group:admins'
      policy: one_factor
    - domain: 'traefik.solutioneer.app'
      subject: 'group:admins'
      policy: one_factor


session:
  name: authelia_session ## Name of the session cookie.
  domain: solutioneer.app  ## Domain to protect.
#  same_site: strict ## Possible options are none, lax, or strict. #todo:(future)
  secret: RPINHeWH4FSEIWeDX7atcLwmYCwZrCRgpZG2NFgTyzbCjwU9v4hSiRRZRnxbCc6N 
    ## todo:(future) Secret can be set using the env variables AUTHELIA_SESSION_SECRET
  expiration: 3600  # 1 hour
  inactivity: 900  # 5 minutes 
  remember_me_duration: 1M 

  redis:
    host: redis
    port: 6379
    maximum_active_connections: 8
    minimum_idle_connections: 0
        
##> SECURITY FEATURE (IMPORTANT)
regulation:
  max_retries: 5 
  find_time: 120 
  ban_time: 600 

storage: ##! encrypt sensitive information in the database. 
  encryption_key: Kg*n#K75IEEst4q1&JlO ## Min 20 chars. #! Required 
  #todo:(future)can be set using the env variables AUTHELIA_STORAGE_ENCRYPTION_KEY 
  mysql:
    host: mysql 
    port: 3306
    database: authelia_db 
    username: authelia_db
    password: 4906131
    timeout: 5s
    
notifier:
  disable_startup_check: false  ##- You can disable the notifier startup check by setting this to true.
  filesystem:
    filename: /config/logs/notification.txt
...
