---
entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
#    tls: {}

serversTransport: 
  insecureSkipVerify: true #> SECURITY: For testing only. False for production.

http:  
  middlewares:
    authelia:
      forwardAuth:
        address: "https://authelia:9091/api/verify?rd=https%3A%2F%2Fauth.solutioneer.app%2F"
        trustForwardHeader: true
        authResponseHeaders:
          - "Remote-User"
          - "Remote-Groups"
          - "Remote-Email"
          - "Remote-Name"
    
    https-redirect:
      #https-redirectscheme:
      redirectScheme:
        scheme: "https"
    default-headers:
      headers:
        frameDeny: true
        sslRedirect: true
        browserXssFilter: true
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 15552000
        customFrameOptionsValue: SAMEORIGIN
        customRequestHeaders:
          X-Forwarded-Proto: https
 
  routers:
    traefik:
      rule: "Host(`traefik.solutioneer.app`)"
      entryPoints:
        - "https"
      service: api@internal
      middlewares:
        - default-headers
        - authelia@file
      tls:
      options: modern@file
      certResolver: letsencrypt
      domains:
        - main: "solutioneer.app"
          sans:
            - "*.solutioneer.app"    
    authelia:
      entryPoints:
        - "https"
      rule: "Host(`auth.solutioneer.app`)"
      service: api@internal
      middlewares:
        - authelia@file
        - default-headers
      tls:
        certResolver: "letsencrypt"
    traefik-local:
      entryPoints:
        - "https"
      rule: "Host(`192.168.68.103:8080`)"
      service: api@internal
      middlewares:
        - autheli@file
        - default-headers
      tls:
        certResolver: "letsencrypt"

certificatesResolvers:
  letsencrypt:
    acme: 
      email: "eduardocy92@gmail.com"
      storage: "/config/acme.json"
      httpChallenge:
        entryPoint: "http"

api:
  dashboard: true
  debug: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: "config/traefik.yml"  

accessLog:
  filePath: "config/access.log"
  format: json
...
